#	Copyright 2016, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: ReplicationController
apiVersion: v1
metadata:
  name: <env>-mongo-<num>
spec:
  replicas: 1
  selector:
    name: <env>-mongo-node-<num>
    role: mongo
    environment: <env>
  template:
    spec:
      containers:
        - name: mongo-node-<num>
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: azure
              mountPath: /mnt/azure
        - name: mongo-sidecar
          image: leportlabs/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=<env>"
      volumes:
        - name: azure
          azureFile:
            secretName: azure-secret
            shareName: <env>-mongo-<num>
            readOnly: false
    metadata:
      labels:
        name: <env>-mongo-node-<num>
        role: mongo
        environment: <env>
